project_id = "xhhcgspdobgmtumzmbjt"

[functions.seed-demo-orgs]
verify_jwt = false

[functions.create-contribution-checkout]
verify_jwt = false

[functions.stripe-contribution-webhook]
verify_jwt = false

[functions.validate-guest-token]
verify_jwt = false

[functions.scrape-workshops]
verify_jwt = false

[functions.seed-demo-data]
verify_jwt = false

[functions.device-heartbeat]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false